swagger: "2.0"
info:
  description: "This is a microservice for manage and find availabilities. It's a component of the **vgr** project."
  version: "1.0.0"
  title: "vgr-availability-svc"
  contact:
    email: "hugo_sale@hotmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8092"
basePath: "/"
tags:
- name: "availabilities"
  description: "Everything about availabilities"
schemes:
- "http"
paths:
  /availabilities:
    get:
      tags:
      - "availabilities"
      summary: "Gets all the existing availabilities."
      description: "Gets all the existing availabilities."
      operationId: "getAllAvailabilities"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Availability"
    post:
      tags:
      - "availabilities"
      summary: "Creates a new availability."
      description: "Creates a new availability."
      operationId: "createAvailability"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Availability object to create"
        required: true
        schema:
          $ref: "#/definitions/Availability"
      responses:
        "400":
          description: "Invalid input"
  /availabilities/{id}:
    get:
      tags:
      - "availabilities"
      summary: "Get an availability by its ID."
      description: "Get an availability by its ID."
      operationId: "getAvailabilityByID"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of availability to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Availability"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Availability not found"
    put:
      tags:
      - "availabilities"
      summary: "Updates an existing availability by its ID."
      description: "Updates an existing availability by its ID."
      operationId: "updateAvailability"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of availability that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Availability object to create"
        required: true
        schema:
          $ref: "#/definitions/Availability"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Availability"
        "400":
          description: "Bad request, invalid given name or ID"
        "404":
          description: "Availability not found"
    delete:
      tags:
      - "availabilities"
      summary: "Deletes an existing availability by its ID."
      description: "Deletes an existing availability by its ID."
      operationId: "deleteAvailability"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of availability to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "204":
          description: "No content, the availability was successfully deleted"
          schema:
            $ref: "#/definitions/Availability"
        "400":
          description: "Bad request, invalid given name or ID"
        "404":
          description: "Availability not found"
definitions:
  Availability:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      name:
        type: "string"
        example: "Available"
externalDocs:
  description: "Find out more about vgr"
  url: "http://github.com/thesuperunknown"
